### ISSUE TITLE
[BUG] multiple bugs in 1.18.2

### ISSUE THREAD

**Issue by ilkerbey-01** [Patbox/get-off-my-lawn-reserved#4] opened 2022-04-09 16:36 UTC
augments pop off after restarting the server and for some reason names of blocks are glitched... also have a crash report....

https://paste.ee/p/XvuvW

**Comment by Patbox** [comment] 2022-04-10 07:15
Could you check if installing this fixes names? https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.10%2B1.18.2/server-translations-api-1.4.10%2B1.18.2.jar

**Comment by ilkerbey-01** [comment] 2022-04-10 09:30
will try, what about other ones?

**Comment by Patbox** [comment] 2022-04-10 10:04
I will need little more time, but I will fix them

**Comment by Patbox** [comment] 2022-04-16 15:55
Fixed on latest (excluding translations issues). They are most likely caused by some other mod, see https://github.com/Patbox/UniversalGraves/issues/71

**Closed by Patbox** 2022-04-16 15:55 UTC
